name = "jwt-worker"
account_id = "394d48aba686b2466fe12e540c5d9466"
workers_dev = true
vars = { PLAID_ORIGIN = "https://sandbox.plaid.com", SENDGRID_DYNAMIC_TEMPLATE="d-5d9795b1c27e4897b6bca60eb519450b", SIGNING_KEY = "secret" }
main = "./src/index"
compatibility_date = "2022-06-18"

[dev]
port = 8790

[env.production]
vars = { PLAID_ORIGIN = "https://production.plaid.com" }
