// Generated by Wrangler on Sun May 12 2024 06:44:30 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
  SENDGRID_LOGIN_TEMPLATE: 'd-678ba471997f44cfa0dc2c01bf824c91';
  SENDGRID_API_KEY: string;
  LOGIN_LINK_SECRET: string;
  STRIPE_API_KEY: string;
}
